name: Release

on:
  push:
    branches:
      - master

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Set up Node@v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make build

    - name: Test
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make test
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Node@v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make generate

    # - name: Generate Docs
    #   run: |
    #     export GOPATH=$HOME/go
    #     export GOBIN=$(go env GOPATH)/bin
    #     export PATH=$PATH:$GOPATH
    #     export PATH=$PATH:$GOBIN
    #     cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
    #     make gen_docs

    - name: Build UI
      run: |
        cd $HOME/go/src/github.com/$GITHUB_REPOSITORY/ui
        npm i
        npm run-script build
        npm run-script lint
  setup-build-deploy:
    name: Deploy to Google App Engine
    needs: [build-api, build-ui]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          mkdir -p $GOPATH/pkg
          mkdir -p $GOBIN
          mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
          mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
          cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
          make generate
          cd ui/
          npm i
          npm run-script build
          rm -rf node_modules public src
          cd ../
          which envsubst
          envsubst < app.template.yaml > app.yaml
          gcloud app deploy --promote --stop-previous-version --quiet
